replicaCount: 1
deploymentName: mirror
namespace: mirror
image:
  repository: wlanboy/mirrorservice
  tag: latest
  pullPolicy: Always

hosts: 
  - mirror.tp.lan
  - mirror.gmk.lan

service:
  port: 8080

persistence:
  enabled: true
  size: 100Mi
  storageClass: local-path

istio:
  gateway: mirror-gateway
  gatewayNamespace: "istio-ingress"

certmanager:
  issuer: local-ca-issuer
  kind: ClusterIssuer
  secretName: mirrorapi-tls
