name: Docker build and publish image to github
on: 
  push:
    tags: 
      - '*g'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      
    - name: Build and publish Docker Image to GitHub Packages Registry
      uses: VaultVulp/gp-docker-action@1.1.7
      with:
        github-token: ${{ github.token }}
        image-name: mirrorservice
        image-tag: latest
        extract-git-tag: false
        dockerfile: Dockerfile
        build-context: .
        pull-image: false
